version: '3.8'

services:
  # Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: nodeapi_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nodeapi_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Nossa API Node.js
  api:
    build: .
    container_name: nodeapi_app
    restart: always
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/nodeapi_db
      - PORT=3000
    depends_on:
      - db

  # Ferramenta visual para o banco
  adminer:
    image: adminer
    container_name: nodeapi_adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  pgdata:
